[tool.isort]
profile = "black"
src_paths = [
    "source/models",
    "source/newtonianvae",

    "source/simulation",
    "source/tool",

    "source/mypython",
]
skip_glob = [
    "*override",
]
known_first_party = [
    "source/mypython"
]

[tool.black]
line-length = 100
extend_exclude = "override/"
