[tool.isort]
profile = "black"
src_paths = [
    "models",
    "nvae",

    "simulation",
    "tool",

    "mypython",
]
skip_glob = [
    "*override",
]

[tool.black]
line-length = 100
extend_exclude = "override/"
