[tool.isort]
profile = "black"
src_paths = [
    "models",
    "nvae",

    "simulation",
    "tool",
]
skip_glob = [
    "*override",
]
known_first_party = [
    "mypython"
]

[tool.black]
line-length = 100
extend_exclude = "override/"
